### PR TITLE
Settings

### PR DESCRIPTION
**Pull request by reichert-p**
New Scene Options Menu 
New Scene Key Binding Menu
Working adaptable key bindings for all Inputs Execpt ENTER and ESCAPE (including Mouse buttons and probably Controller Buttons)
Working adaptable key bindings for Wizard Movement, shooting and pause button

### CODE REVIEW

**Review by Leonneu — CHANGES_REQUESTED** [review]
I don't think I should be able to change all the controls to one key. Maybe check if the change is valid or swap keys if there is a conflict
Looks good otherwise

**Comment by reichert-p** [comment]
> I don't think I should be able to change all the controls to one key. Maybe check if the change is valid or swap keys if there is a conflict Looks good otherwise

kek

**Comment by reichert-p** [comment]
if somebody thinks this is not User friendly, please feel free to add a detailed issue on youtrack including design proposals. I only accept functional criticism 😄

**Review by Leonneu — APPROVED** [review]
Very Cool.

**Pull request merged**
